failed_load_bs_settings = "Failed to load bootstrap settings: {{.Err}}"
failed_init = "Failed to initialize: {{.Err}}"
fetching_launcher_updates = "Fetching launcher updates..."
update_button = "Update!"
skip_button = "Skip"
installed_version = "Installed version: {{.Version}}"
latest_version = "Latest version: {{.Version}}"
fail_rename_old = "Failed to rename old launcher:"
fail_delete_old = "Failed to delete previous launcher version:"
not_available_os = "Launcher not available for architecture"
downloading = "Downloading new launcher..."
elapsed_time = "Elapsed time:"
failed_download = "Failed to download new launcher:"
hash_not_match = "Launcher corrupted and failed to download a new one"
newly_corrupted = "The newly downloaded launcher is corrupted. You might want to contact the admin."