failed_load_bs_settings = "Echec du chargement des paramètres Bootstrap: {{.Err}}"
failed_init = "Échec de l'initialisation: {{.Err}}"
fetching_launcher_updates = "Récupération des mise à jour launcher..."
update_button = "Mettre à jour!"
skip_button = "Ignorer"
installed_version = "Version installée: {{.Version}}"
latest_version = "Nouvelle version: {{.Version}}"
fail_rename_old = "Échec du renommage de l'ancienne verison:"
fail_delete_old = "Échec de la suppression de l'ancienne version:"
not_available_os = "Launcher non disponible pour votre système"
downloading = "Téléchargement du nouveau launcher..."
elapsed_time = "Temps écoulé:"
fail_download = "Échec du téléchargement du launcher:"
hash_not_match = "Launcher corrompu, et échec du téléchargement"
newly_corrupted = "Le nouveau launcher est corrompu. Vous devriez contacter un admin"