name: RetroNautsMC Bootstrapper

on:
  push:
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o RetroNautsMC-Launcher -v ./... 

    - name: Upload Build Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: RetroNautsMC-${{ matrix.os }}
        path: |
          ./RetroNautsMC-Launcher*
